# Generated by Django 3.2.3 on 2021-08-06 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RegionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('recipe', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('ingredients', models.ManyToManyField(to='api.Ingredient')),
                ('region', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.regiontype')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.mealtype')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('commented_meal', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.mealtype')),
            ],
        ),
    ]
