# Generated by Django 3.2.3 on 2021-08-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210810_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ingredients_amount',
            field=models.TextField(default='hi'),
        ),
    ]
