# Generated by Django 3.2.3 on 2021-08-30 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_meal_ingredients_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='ingredients_names',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='ingredients_amount',
            field=models.IntegerField(),
        ),
    ]
