# Generated by Django 3.2.3 on 2021-10-27 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20211027_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='amount',
        ),
    ]
