# Generated by Django 3.2.3 on 2021-10-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_meal_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngAmount',
        ),
    ]
