# Generated by Django 3.2.3 on 2021-10-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211027_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='amount',
        ),
        migrations.DeleteModel(
            name='IngAmount',
        ),
    ]
