# Generated by Django 3.2.3 on 2021-10-27 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211027_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ingredients_names',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='region',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='RegionType',
        ),
    ]
