# Generated by Django 3.2.3 on 2021-10-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20211028_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='amount',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='IngAmount',
        ),
    ]
