# Generated by Django 3.2.3 on 2021-10-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_meal_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='amount',
        ),
        migrations.AddField(
            model_name='meal',
            name='amout',
            field=models.JSONField(null=True),
        ),
    ]
