# Generated by Django 3.2.8 on 2021-10-31 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20211031_1320'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngAmount',
        ),
    ]
