# Generated by Django 3.2.8 on 2021-10-31 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_ingredient_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
        migrations.CreateModel(
            name='IngredientAm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=None)),
                ('ingredient_name', models.ManyToManyField(to='api.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='ing_amount',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.ingredientam'),
        ),
    ]
