# Generated by Django 3.2.8 on 2021-10-31 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20211031_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ing_amount',
        ),
        migrations.AddField(
            model_name='ingredientam',
            name='meal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.meal'),
        ),
        migrations.RemoveField(
            model_name='ingredientam',
            name='ingredient_name',
        ),
        migrations.AddField(
            model_name='ingredientam',
            name='ingredient_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.ingredient'),
        ),
    ]
