# Generated by Django 3.2.8 on 2021-11-01 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_ingredientam_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientam',
            options={'ordering': ['meal']},
        ),
    ]
