# Generated by Django 3.2.8 on 2021-11-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_rename_ingredientam_ingredientamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ingredients_amount',
        ),
    ]
